gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

pvrezcomment_add:
    pattern:  /comment/add/{contentId}
    defaults: { _controller: pvrEzCommentBundle:Comment:addComment }
    requirements:
        _method: POST
        contentId: \d+

# @TODO: merge both route
pvrezcomment_approve:
    pattern: /comment/approve/{contentId}/{sessionHash}
    defaults: { _controller: pvrEzCommentBundle:Comment:approve }
    requirements:
        contentId: \d+

pvrezcomment_reject:
    pattern: /comment/reject/{contentId}/{sessionHash}
    defaults: { _controller: pvrEzCommentBundle:Comment:reject }
    requirements:
        contentId: \d+
